from . import log_message as log_message
from collections.abc import Generator

class _GeneratorContext:
    def __init__(self, execution_context) -> None: ...
    def init_stack(self, generator) -> None: ...
    def in_generator(self, generator) -> Generator[None, None, None]: ...

class GeneratorSupportNotEnabled(Exception): ...

def eliot_friendly_generator_function(original): ...
