from _typeshed import Incomplete
from pyrsistent import PClass

class Future: ...

class _RunWithEliotContext(PClass):
    task_id: Incomplete
    func: Incomplete
    key: Incomplete
    dependencies: Incomplete
    def __eq__(self, other): ...
    def __ne__(self, other): ...
    def __hash__(self): ...
    def __call__(self, *args, **kwargs): ...

def compute_with_trace(*args): ...
def persist_with_trace(*args): ...
