from . import addDestination as addDestination, removeDestination as removeDestination
from ._output import FileDestination as FileDestination
from twisted.application.service import Service

class ThreadedWriter(Service):
    name: str
    def __init__(self, destination, reactor) -> None: ...
    def startService(self) -> None: ...
    def stopService(self): ...
    def __call__(self, data) -> None: ...

class ThreadedFileWriter(ThreadedWriter):
    def __init__(self, logFile, reactor) -> None: ...
    def stopService(self): ...
