from ._action import TaskLevel as TaskLevel, WrittenAction as WrittenAction
from ._message import WrittenMessage as WrittenMessage
from _typeshed import Incomplete
from collections.abc import Generator
from pyrsistent import PClass

class Task(PClass):
    def root(self): ...
    def is_complete(self): ...
    def add(self, message_dict): ...

class Parser(PClass):
    def add(self, message_dict): ...
    def incomplete_tasks(self): ...
    @classmethod
    def parse_stream(cls, iterable) -> Generator[Incomplete, None, None]: ...
